import { useCallback, useRef, useState } from 'react'
import { ExportButton } from './components/ExportButton'
import { ImageUploader } from './components/ImageUploader'
import { IntensitySlider } from './components/IntensitySlider'
import { LutUploader } from './components/LutUploader'
import { PreviewCanvas } from './components/PreviewCanvas'
import type { CubeLUT } from './core/cubeParser'
import { serializeCube } from './core/cubeSerializer'
import { generateLUTFromImagePair } from './core/lutGenerator'

const LUT_GENERATION_MAX_EDGE = 1024

function getScaledSize(width: number, height: number): { width: number; height: number } {
  const maxEdge = Math.max(width, height)
  if (maxEdge <= LUT_GENERATION_MAX_EDGE) {
    return { width, height }
  }

  const scale = LUT_GENERATION_MAX_EDGE / maxEdge
  return {
    width: Math.round(width * scale),
    height: Math.round(height * scale),
  }
}

function drawImageToImageData(image: HTMLImageElement, width: number, height: number): ImageData {
  const canvas = document.createElement('canvas')
  canvas.width = width
  canvas.height = height

  const context = canvas.getContext('2d')
  if (!context) {
    throw new Error('无法初始化 Canvas 2D 上下文。')
  }

  context.drawImage(image, 0, 0, width, height)
  return context.getImageData(0, 0, width, height)
}

function createPairedImageData(original: HTMLImageElement, filtered: HTMLImageElement): {
  originalData: ImageData
  filteredData: ImageData
} {
  const originalAspect = original.naturalWidth / original.naturalHeight
  const filteredAspect = filtered.naturalWidth / filtered.naturalHeight

  if (Math.abs(originalAspect - filteredAspect) > 0.02) {
    throw new Error('原图和效果图的宽高比不一致，无法可靠生成 LUT。')
  }

  const { width, height } = getScaledSize(original.naturalWidth, original.naturalHeight)

  return {
    originalData: drawImageToImageData(original, width, height),
    filteredData: drawImageToImageData(filtered, width, height),
  }
}

function downloadTextFile(text: string, fileName: string, mimeType: string): void {
  const blob = new Blob([text], { type: mimeType })
  const url = URL.createObjectURL(blob)
  const link = document.createElement('a')
  link.download = fileName
  link.href = url
  link.click()
  URL.revokeObjectURL(url)
}

function App() {
  const [image, setImage] = useState<HTMLImageElement | null>(null)
  const [imageName, setImageName] = useState<string>('')
  const [filteredReferenceImage, setFilteredReferenceImage] = useState<HTMLImageElement | null>(null)
  const [filteredReferenceName, setFilteredReferenceName] = useState<string>('')
  const [lut, setLut] = useState<CubeLUT | null>(null)
  const [lutName, setLutName] = useState<string>('')
  const [generatedCubeText, setGeneratedCubeText] = useState<string>('')
  const [generatedLutSize, setGeneratedLutSize] = useState(16)
  const [intensity, setIntensity] = useState(100)
  const [compareMode, setCompareMode] = useState(false)
  const [error, setError] = useState<string>('')
  const canvasRef = useRef<HTMLCanvasElement | null>(null)

  const handleCanvasReady = useCallback((canvas: HTMLCanvasElement | null) => {
    canvasRef.current = canvas
  }, [])

  const generateCubeFromPair = () => {
    if (!image || !filteredReferenceImage) {
      setError('请先上传原图和滤镜效果图。')
      return
    }

    try {
      const { originalData, filteredData } = createPairedImageData(image, filteredReferenceImage)
      const generatedLut = generateLUTFromImagePair(originalData, filteredData, {
        size: generatedLutSize,
        title: 'Generated by alpha-z',
      })
      const cubeText = serializeCube(generatedLut)

      setLut(generatedLut)
      setLutName(`生成的 ${generatedLutSize}x LUT`)
      setGeneratedCubeText(cubeText)
      setIntensity(100)
      setError('')
      downloadTextFile(cubeText, 'alpha-z-generated.cube', 'text/plain;charset=utf-8')
    } catch (generationError) {
      const message = generationError instanceof Error ? generationError.message : '生成 CUBE 文件失败。'
      setError(message)
    }
  }

  return (
    <main className="app">
      <header className="app-header">
        <div>
          <h1>
            <span className="codicon codicon-symbol-color" aria-hidden="true" />
            alpha-z
          </h1>
          <p>浏览器端 LUT 滤镜编辑器</p>
        </div>
      </header>

      <div className="workspace">
        <aside className="sidebar">
          <ImageUploader
            label="原图"
            title="拖入或选择原图"
            onImageLoaded={(loadedImage, fileName) => {
              setImage(loadedImage)
              setImageName(fileName)
              setError('')
            }}
            onError={setError}
          />

          <LutUploader
            onLutLoaded={(loadedLut, fileName) => {
              setLut(loadedLut)
              setLutName(fileName)
              setGeneratedCubeText('')
              setError('')
            }}
            onError={setError}
          />

          <section className="generator-panel">
            <h2>
              <span className="codicon codicon-symbol-color" aria-hidden="true" />
              从效果图生成 CUBE
            </h2>
            <ImageUploader
              label="效果图"
              title="拖入或选择滤镜效果图"
              helper="需与原图为同一画面"
              iconClass="codicon-preview"
              onImageLoaded={(loadedImage, fileName) => {
                setFilteredReferenceImage(loadedImage)
                setFilteredReferenceName(fileName)
                setError('')
              }}
              onError={setError}
            />
            <label className="generator-size">
              <span>生成尺寸</span>
              <select
                value={generatedLutSize}
                onChange={(event) => setGeneratedLutSize(Number(event.currentTarget.value))}
              >
                <option value={16}>16 x 16 x 16</option>
                <option value={32}>32 x 32 x 32</option>
              </select>
            </label>
            <button className="secondary-button" type="button" disabled={!image || !filteredReferenceImage} onClick={generateCubeFromPair}>
              <span className="codicon codicon-export" aria-hidden="true" />
              生成并下载 CUBE
            </button>
            {generatedCubeText ? (
              <button
                className="ghost-button"
                type="button"
                onClick={() => downloadTextFile(generatedCubeText, 'alpha-z-generated.cube', 'text/plain;charset=utf-8')}
              >
                重新下载生成的 CUBE
              </button>
            ) : null}
          </section>

          {error ? <div className="error-message">{error}</div> : null}

          <div className="file-info">
            <div>
              <span>
                <span className="codicon codicon-file-media" aria-hidden="true" />
                原图
              </span>
              <strong title={imageName || undefined}>{imageName || '未加载'}</strong>
            </div>
            <div>
              <span>
                <span className="codicon codicon-preview" aria-hidden="true" />
                效果图
              </span>
              <strong title={filteredReferenceName || undefined}>{filteredReferenceName || '未加载'}</strong>
            </div>
            <div>
              <span>
                <span className="codicon codicon-symbol-color" aria-hidden="true" />
                LUT
              </span>
              <strong title={lutName || undefined}>{lutName || '仅显示原图'}</strong>
            </div>
            {lut ? (
              <div>
                <span>
                  <span className="codicon codicon-settings-gear" aria-hidden="true" />
                  LUT 尺寸
                </span>
                <strong>
                  {lut.size} x {lut.size} x {lut.size}
                </strong>
              </div>
            ) : null}
          </div>

          <IntensitySlider value={intensity} onChange={setIntensity} disabled={!image || !lut} />

          <label className="toggle-row">
            <input
              type="checkbox"
              checked={compareMode}
              disabled={!image || !lut}
              onChange={(event) => setCompareMode(event.currentTarget.checked)}
            />
            <span className="toggle-label">
              <span className="codicon codicon-compare-changes" aria-hidden="true" />
              对比原图 / 滤镜效果
            </span>
          </label>

          <ExportButton getCanvas={() => canvasRef.current} disabled={!image} />
        </aside>

        <section className="preview-panel">
          <PreviewCanvas
            image={image}
            lut={lut}
            intensity={intensity}
            compareMode={compareMode}
            onCanvasReady={handleCanvasReady}
          />
        </section>
      </div>
    </main>
  )
}

export default App
